# Generated by Django 6.0 on 2026-03-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationcompte', '0003_notification_image'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationcompte.seance'),
        ),
    ]
