# Generated by Django 6.0 on 2026-03-09 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationcompte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='seances_reservees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seance',
            name='places_disponibles',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
