# Generated by Django 6.0 on 2026-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationcompte', '0003_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
